### PR TITLE
KL Divergence optimization

### PR DESCRIPTION
**Pull request by gottacatchenall**

### CODE REVIEW

**Comment by tpoisot** [comment]
I like the idea - this is what Fauxcurrence uses as well. One thing that may be useful is to use Jensen-Shannon instead, which is symmetrical, and bounded (to 1 when using log2, to log2 when using log2). The square root of JS is also a distance (that is bounded to 1 when using log2, which is really nice in terms of giving a sense of the quality of the fit).

Thoughts?

**Comment by gottacatchenall** [comment]
Seems like it makes sense to use JS distance. The only issue I'm running into is whencomputing JS-div by definition as 

$$JS(P,Q) = \frac{1}{2}KL(P,M) + \frac{1}{2}KL(Q,M)$$ where $M=\frac{1}{2}(P+Q)$

when using a `MixtureModel` from `Distributions.jl` for `M`, this works fine for `Normal` distributions but for `MvNormal`s the methods within `kldivergence` [calls](https://github.com/JuliaStats/Distributions.jl/blob/630e1c908b82bc2702cc7f29616cd22e5f94ab04/src/functionals.jl#L29) sample expectation values (presumably because it can't be computed analytically), so there is variance in JS measures on the same pair of distributions. With enough samples it goes down ofc, but there is going to be a trade-off in terms of speed of eval.  Around $10^5$ samples is relatively stable for 5 layers, but this could be variable depending on the input number of layers.

**Comment by gottacatchenall** [comment]
Also I think it may be worth import SA/other methods from Optim.jl instead of rewriting tools to do fit diagnostics from scratch

**Comment by gottacatchenall** [comment]
A long-term development goal is to include many of the methods that rely on optimizing some measure of difference, but these require gradient-free optimization methods which bring their own headaches w/r/t diagnostics. Not in the cards for v1.0

**Pull request closed without merging**
